From ktmrmshk/py3:latest

RUN pip3 install setuptools \
      && pip3 install flask \
      && git clone https://github.com/ktmrmshk/Dresp.git 

EXPOSE 5000

#CMD ["/usr/bin/python3", "/Dresp/dresp/drespweb.py"]
